name: CI
on: [push]
jobs:
  whole:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: format
        run: npm run format
        env:
          CI: true

  functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: ./firebase/functions
        env:
          CI: true

      - name: build
        run: npm run build
        working-directory: ./firebase/functions
        env:
          CI: true

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: ./client
        env:
          CI: true

      - name: build
        run: npm run build
        working-directory: ./client
        env:
          CI: true
